# Generated by Django 4.2.9 on 2024-01-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('first_name', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True, verbose_name='азыркы учурда иштейт')),
                ('image', models.ImageField(blank=True, upload_to='p/%Y/%m/%d')),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт')),
            ],
        ),
        migrations.CreateModel(
            name='New_dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='new_dishes/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restaura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restauran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='im/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='i/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='Наличие')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавление')),
                ('uploaded', models.DateTimeField(auto_now=True, verbose_name='Изменение')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'ordering': ['name'],
                'index_together': {('id', 'slug')},
            },
        ),
    ]
